name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  auto_class_in_file:
    name: Test ${{ matrix.config.name }} OS can handle automatic class generation for python ${{matrix.python.version}}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - {
          #   name: darwin,
          #   os: macos-latest,
          # }
          - {
            name: windows,
            os: windows-2022,
          }
          # - { 
          #  name: ubuntu,
          #   os: ubuntu-latest,
          # }
        python:
          - {
            name: cp39,
            version: '3.9',
          }  
          - {
            name: cp313,
            version: '3.13',
          }  

    steps:

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools gymnasium

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Install wheel
        shell: bash
        run: |
          python -m pip install dist/*.whl --user
          pip freeze

      - name: Test the automatic generation of classes in the env folder
        run: |
          python -m unittest grid2op.tests.automatic_classes
